Feature/#7 save cookie option
TourmalineCore/TourmalineCore.AspNetCore.JwtAuthentication pull request #8
Opened 2021-04-07 09:08 UTC by nikitamedvedev

2021-04-12 05:44 UTC, Koval1997 commented on JwtAuthentication.Core/ApplicationBuilderExtension.cs
> +                .UseMiddleware<CookieTokenMiddleware>(options);
Два раза вызываешь

2021-04-12 05:44 UTC, Koval1997 commented on JwtAuthentication.Core/Middlewares/CookieLoginMiddleware.cs
> +                Console.WriteLine($"Login: {_options.Key}");
Надо ли что-то в консоль писать?

2021-04-12 05:44 UTC, Koval1997 commented on JwtAuthentication.Core/Middlewares/CookieTokenMiddleware.cs
> +            Console.WriteLine($"Token: {_options.Key}");
Аналогично

2021-04-27 11:45 UTC, vvvictor07 reviewed
Code cleanup is needed

2021-04-27 11:45 UTC, vvvictor07 commented on JwtAuthentication.Core/Middlewares/LoginWithCookieMiddleware.cs
> +                context.Response.StatusCode = 401;
```suggestion
                context.Response.StatusCode = StatusCodes.Status401Unauthorized;
```

2021-04-27 11:45 UTC, vvvictor07 commented on README.md
> +## Cookie
I think the logical structure should be fixed (we need to group two methods of jwt transport via headers and via cookies )

2021-04-27 12:17 UTC, vvvictor07 requested changes

2021-04-27 12:17 UTC, vvvictor07 commented on README.md
>  To start using JWT-based authentication, need to use one method in the Startup.cs file.
```suggestion
To start using JWT-based authentication, you need to use one method in the Startup.cs file.
```

2021-04-27 12:17 UTC, vvvictor07 commented on README.md
> +This package also allows you to store the received token in a cookie. To do that you need to use Cookie login middleware instead of default login. After successful login the token will be added to a
```suggestion
This package also allows you to store the received token in a cookie. To do that you need to use Cookie login middleware instead of default login. After successful login the token will be added to a cookie, that user will receive in a response. Then they can use this cookie for the authentication instead of writing the token to the Authentication header of every request. 
```

2021-04-27 12:21 UTC, vvvictor07 approved these changes

2021-04-27 12:37 UTC, merged